### ISSUE TITLE
mac kurulum gereksinimleri

### ISSUE THREAD

**Issue by ahmetozalp** [antichown/0x94TR#1]
Merhaba Burp kullanımını az çok biliyorum ama kafamı karıştıran dosyalardaki linuxwine dosyası ne içindir? gereklimidir?
gerekli degilse klasoru indirip burp ile açıp ekran resimlerindeki. gibi yapmam yeterli olur mu?

**Comment by antichown** [comment]
Burp kullanımı için o dosya gerekli değildir kardeşim zaten  kafalar karışmasın diye sildim. Eklentiyi indirin ve ekran resmindeki gibi yüklemeyi gerçekleştirip kullanabilirsiniz.
